# Task 4: Using print statements form a tree in the console output. This kind of result

print(
    "\033[0;31m                         T                              \n"
    "                        TTT                             \n"
    "                       TTTTT                            \n"
    "                      TTTTTTT                           \n"
    "                     TTTTTTTTT                          \n"
    "                    TTTTTTTTTTT                         \n"
    "                   TTTTTTTTTTTTT                        \n"
    "                  TTTTTTTTTTTTTTT                       \n"
    "                     TTTTTTTTT                          \n"
    "                    TTTTTTTTTTT                         \n"
    "                   TTTTTTTTTTTTT                        \n"
    "                  TTTTTTTTTTTTTTT                       \n"
    "                 TTTTTTTTTTTTTTTTT                      \n"
    "                TTTTTTTTTTTTTTTTTTT                     \n"
    "               TTTTTTTTTTTTTTTTTTTTT                    \n"
    "              TTTTTTTTTTTTTTTTTTTTTTT                   \n"
    "             TTTTTTTTTTTTTTTTTTTTTTTTT                  \n"
    "                TTTTTTTTTTTTTTTTTTT                     \n"
    "               TTTTTTTTTTTTTTTTTTTTT                    \n"
    "              TTTTTTTTTTTTTTTTTTTTTTT                   \n"
    "             TTTTTTTTTTTTTTTTTTTTTTTTT                  \n"
    "            TTTTTTTTTTTTTTTTTTTTTTTTTTT                 \n"
    "           TTTTTTTTTTTTTTTTTTTTTTTTTTTTT                \n"
    "          TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT               \n"
    "         TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT              \n"
    "        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT             \n"
    "       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT            \n"
    "                         TTT                            \n"
    "                         TTT                            \n"
    "                         TTT                            \n"
    "                    TTTTTTTTTTTTT                       \n"
)
